=== Tejaswini-patil23/WT-practicals/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="department" type="xs:string"/>
                            <xs:element name="designation" type="xs:string"/>
                            <xs:element name="salary" type="xs:decimal"/>
                            <xs:element name="email" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="empId"
                                      type="xs:string"
                                      use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Tejaswini-patil23/WT-practicals/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employees.xsl"?>

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="employees.xsd">

    <employee empId="101">
        <name>Tejaswini Patil</name>
        <department>IT</department>
        <designation>Software Engineer</designation>
        <salary>65000</salary>
        <email>tejaswini@gmail.com</email>
    </employee>

    <employee empId="102">
        <name>Divya</name>
        <department>HR</department>
        <designation>HR Manager</designation>
        <salary>72000</salary>
        <email>Divya@gmail.com</email>
    </employee>

    <employee empId="103">
        <name>Dipali</name>
        <department>Programming</department>
        <designation>Programmer</designation>
        <salary>90000</salary>
        <email>Dipali@gmail.com</email>
    </employee>

</employees>
